config/routes.rb
Travel::Application.routes.draw do
  
  resources 'categories'
  resources 'messages'
  resources :users
  resources :sessions, only: [ :new, :create, :destroy ]

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'messages#new'

  resources :countries do
    resources :comments
  end
  

end

app/models/country.rb
# encoding: UTF-8
class Country < ActiveRecord::Base
  extend FriendlyId
  friendly_id :url_name, use: :slugged
  has_many :comments, dependent: :destroy
  belongs_to :category, :foreign_key => 'category_id'

  attr_accessible :content, :url_name, :title, :category_id
  
  VALID_URL_NAME = /[A-Za-z]/i

  validates :title ,    presence: true, 
                        length: { minimum: 3, maximum: 50 },
                        uniqueness: true
  validates :url_name,  presence: true, 
                        length: { minimum: 4, maximum: 25 },
                        format: { with: VALID_URL_NAME, message: "Только английскими буквами" }, 
                        uniqueness: true
  validates :content,   presence: true,
                        length: { maximum: 12000 }

  default_scope order: 'countries.title ASC'
end

app/controllers/countries_controller.rb
# encoding: UTF-8
class CountriesController < ApplicationController
  before_filter :signed_in_user,  only: [:new, :create, :edit, :destroy]
  before_filter :country,         only: [:show, :edit, :update, :destroy]
  before_filter :categories
  #add_breadcrumb "Главная", :root_path
  
  def new
    @country = Country.new
  end

  def create
    @country = Country.new(params[:country])
    
    if @country.save
      flash[:success] = "Страна успешно добавлена"
      redirect_to country_path(@country)
    else
      render 'new'
    end
  end
  
  def show
    #add_breadcrumb "#{@country.title}", :country_path
  end
  
  def index
    countries
  end
  
  def edit
  end
  
  def update
    if @country.update_attributes(params[:country])
      flash[:success] = "Обновление прошло успешно"
      redirect_to country_path(@country)
    else
      render 'edit'
    end
  end

  def destroy
    @country.destroy
    flash[:success] = "Страна удалена"
    redirect_to :action => :index
  end
end

app/helpers/countries_helper.rb
module CountriesHelper

  def country
    @country = Country.find(params[:id])
  end
	
end

app/views/countries/_add_comment.html.haml
%h2 Оставить комментарий:
= form_for([@country, @country.comments.build]) do |f|
    = render 'shared/error_messages', object: f.object
    /= f.label :commenter, "Имя"
    = f.text_field :commenter, placeholder: "Имя не более 25 символов" , class: "input-xlarge"
    /= f.label :body, "Текст"
    = f.text_area :body, placeholder: "Текст не более 500 символов", rows: 5
    = f.submit "Отправить", class: "btn btn-large btn-primary"

app/views/countries/_comments.html.haml
%h2 Комментарии
- if @country.comments.count != 0
  - @country.comments.each do |comment|
    .row-fluid
      .span3
        %p
          %strong
            = comment.commenter
          %br
          %small.muted
            = comment.created_at.strftime("%d.%m.%Y в %k:%M:%S")
      .span9
        %p
          = comment.body
    %hr.comment
    - if signed_in? && current_user.admin?
      = link_to "Удалить комментарий", [comment.country, comment],        confirm: "Вы уверены?", method: :delete, class: "pull-right"
-else
  .center
    %p Еще нет ни одного комментария. Будь первым!

app/views/countries/_fields.html.haml
= render 'shared/error_messages', object: f.object
= f.label :title, "Название страны"
= f.text_field :title, class: "input-xlarge"
= f.label :url_name, "Название страны на английском языке"
= f.text_field :url_name, class: "input-xlarge"
= f.label :category_id, "Категория"
.input-xlarge
  = f.collection_select :category_id, Category.all, :id, :title
= f.label :content, "Содержимое статьи"
= f.text_area :content, :class => "tinymce", :rows => 60, :cols => 120
= tinymce

app/views/countries/edit.html.haml
- provide(:title, 'Изменить статью')
%h1 Изменить статью
.row-fluid
  .span12
    = form_for(@country) do |f|
      = render 'fields', f: f
      = f.submit "Сохранить", class: "btn btn-large btn-primary"

app/views/countries/index.html.haml
= render 'shared/carusel'
%h1 Все страны по категориям
.span6.offset2  
  %table
    - @categories.each do |category|
      .offset0
        %tr
        %th
          %h2
            = category.title
        %td
          - @countries.each do |country|
            - if country.category.id == category.id;
              /.center
              %h3
                = link_to country.title, country_path(country)

app/views/countries/new.html.haml
- provide(:title, 'Добавить страну')
%h1 Добавить страну
.row-fluid
  .span12
    = form_for(@country) do |f|
      = render 'fields', f: f
      = f.submit "Добавить статью", class: "btn btn-large btn-primary"

app/views/countries/show.html.haml
- provide(:title, @country.title)
- if File.exist?("app/assets/images/"+@country.slug + ".jpg")
  = image_tag(@country.slug + ".jpg", alt: @country.title, class: "img-country")
%h1
  = @country.title
.row-fluid
  .pull-right
    %span.label.label-inverse.label-category
      = raw link_to @country.category.title, category_path(@country.category)
.row-fluid
  %p
    = raw @country.content
  - if signed_in? && current_user.admin?
    %p
      = link_to 'Редактировать', edit_country_path(@country)
      -if current_user.name == "admin"
        | 
        = link_to 'Удалить', { :action => :destroy, :id => @country.id }, :method => :delete, :confirm => 'Are you sure?'
.row-fluid
  = render 'comments'
  %br
  = render 'add_comment'