config/routes.rb
Travel::Application.routes.draw do
  
  resources 'categories'
  resources 'messages'
  resources :users
  resources :sessions, only: [ :new, :create, :destroy ]

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'messages#new'

  resources :countries do
    resources :comments
  end
  

end

app/models/category.rb
# encoding: UTF-8
class Category < ActiveRecord::Base
  extend FriendlyId
	
  attr_accessible :slug, :title, :url_title
  friendly_id :url_title, use: :slugged
  has_many :countries

  VALID_URL_TITLE = /[A-Za-z]/i

  validates :title, presence: true
  validates :url_title, presence: true,
            format: { with: VALID_URL_TITLE, message: "Только английскими буквами" }, 
            uniqueness: true

  default_scope order: 'categories.title ASC'

end

app/controllers/categories_controller.rb
# encoding: UTF-8
class CategoriesController < ApplicationController
  before_filter :categories, only: [:index,:show]
  before_filter :category, only: [:show, :edit, :update, :destroy]

  def index
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params[:category])
    if @category.save
      flash[:success] = "Категория успешно добавлена"
      redirect_to new_category_path
    else
      render 'new'
    end
  end

  def show
    @countries = Country.where("category_id = ?", @category.id)
  end

  def edit
  end

  def update
    if @category.update_attributes(params[:category])
      flash[:success] = "Категория успешно изменена"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy
    flash[:success] = "Категория успешно удалена"
    redirect_to category_path
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper

  def category
    @category = Category.find(params[:id])
  end
	
end

app/views/categories/_fields.html.haml
= render 'shared/error_messages', object: f.object
= f.label :title, "Название категории"
= f.text_field :title, class: "input-xlarge"
= f.label :url_title, "Название категории на английском языке"
= f.text_field :url_title, class: "input-xlarge"

app/views/categories/edit.html.haml
- provide(:title, 'Изменить категорию')
%h1 Изменить категорию
.row-fluid
  .span6.offset3
    = form_for(@category) do |f|
      = render 'fields', f: f
      %br
      = f.submit "Изменить категорию", class: "btn btn-large btn-primary"

app/views/categories/index.html.haml
%h1 Categories#index
%p Find me in app/views/categories/index.html.haml

app/views/categories/new.html.haml
- provide(:title, 'Добавить категорию')
%h1 Добавить категорию
.row-fluid
  .span6.offset3
    = form_for(@category) do |f|
      = render 'fields', f: f
      %br
      = f.submit "Добавить категорию", class: "btn btn-large btn-primary"

app/views/categories/show.html.haml
- provide(:title, @category.title)
%h1 
  = @category.title
- @countries.each do |country|
  %h4
    = link_to country.title, country_path(country)
  %p
    = raw truncate(country.content, :length => 500, :omission => "...")
    = link_to "Читать далее ...", country_path(country)
  %hr