config/routes.rb
Travel::Application.routes.draw do
  
  resources 'categories'
  resources 'messages'
  resources :users
  resources :sessions, only: [ :new, :create, :destroy ]

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'messages#new'

  resources :countries do
    resources :comments
  end
  

end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    %p
      Сделал
      = link_to "Vitaminus", "http://goo.gl/3fx5T", class: "powered_by", target: "_blank"
  %nav
    %ul
      %li= link_to "О нас", about_path
      %li= link_to "Обратная связь", contact_path

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top
  .navbar-inner
    .container-fluid
      = link_to "Travel", root_path, id: "logo"
      %nav
        %ul.nav.pull-right
          %li= link_to "Главная", root_path
          %li= link_to "Страны", countries_path
          %li= link_to "Обратная связь", contact_path
          - if signed_in?
            - if current_user.admin?
              %li#fat-menu.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  Учетная запись
                  %b.caret
                %ul.dropdown-menu
                  %li#hello= link_to "Привет " + current_user.name, '#'
                  %li= link_to "Добавить страну", new_country_path
                  /%li= link_to "Добавить категорию", new_category_path
                  %li= link_to "Пользователи", users_path
                  %li= link_to "Профиль", current_user
                  %li= link_to "Внести изменения", edit_user_path(current_user)
                  %li.divider
                  %li
                    = link_to "Выйти", signout_path, method: "delete"
            - else
              %li
                = link_to "Выйти", signout_path, method: "delete"
          - else
            %li
              = link_to "Вход", signin_path
            /%li= link_to "Регистрация", signup_path

app/views/layouts/_menu.html.haml
- cache do
  %h2 Категории
  %ul.nav.nav-tabs.nav-stacked
    - @categories.each do |category|
      %li
        = link_to category.title, category_path(category)

app/views/layouts/_shim.html.haml
/[if lt IE 9]
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .container-fluid
      .row-fluid
        .span3
          = render 'layouts/menu'
        .span9
          %ul.breadcrumbs
            = render_breadcrumbs :separator => ' / '
          - flash.each do |key, value|
            = content_tag(:div, value, class: "alert alert-#{key}")
          = yield
      .row-fluid
        = render 'layouts/footer'
        = debug(params) if Rails.env.development?